// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIp40PjWvATVlA3Ym1-VQW6addRVBC_aM',
    appId: '1:823824498745:web:9721da24c8f9109f374de8',
    messagingSenderId: '823824498745',
    projectId: 'social-app-a28d4',
    authDomain: 'social-app-a28d4.firebaseapp.com',
    storageBucket: 'social-app-a28d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJVR86pWU5smjsNd7e2eitRt7IwwDCMvo',
    appId: '1:823824498745:android:ecf00e900cd38ee3374de8',
    messagingSenderId: '823824498745',
    projectId: 'social-app-a28d4',
    storageBucket: 'social-app-a28d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl3GbHUyyPX82DximdPnPlK6KxAMkveRg',
    appId: '1:823824498745:ios:05489ec821c8831b374de8',
    messagingSenderId: '823824498745',
    projectId: 'social-app-a28d4',
    storageBucket: 'social-app-a28d4.appspot.com',
    iosClientId: '823824498745-legosbvvl99sb6587l5283ooir27mhdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl3GbHUyyPX82DximdPnPlK6KxAMkveRg',
    appId: '1:823824498745:ios:c079be02a7bda46a374de8',
    messagingSenderId: '823824498745',
    projectId: 'social-app-a28d4',
    storageBucket: 'social-app-a28d4.appspot.com',
    iosClientId: '823824498745-rgp6ra2j386dn5uh9eg7mv4mucgnabto.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
